---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag
  labels:
    app: rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag
  template:
    metadata:
      labels:
        app: rag
    spec:
      nodeSelector:
        nvidia.com/gpu.count: "1"
      containers:
      - name: rag
        image: quay.io/eformat/ramalama-demo-rag:latest
        pullPolicy: Always
        command: ["/bin/bash", "-c", "nohup llama-server --port 8000 --model /models/model.file --ctx-size 2048 --temp 0.2 -ngl 999 --threads 10 --host 0.0.0.0 &> /tmp/llama-server.log & rag_framework serve /rag/vector.db"]
        ports:
        - containerPort: 8080
        resources:
          limits:
            nvidia.com/gpu: 1
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
